<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Helvetica, Arial, sans-serif; font-size: 11px; color: #111827; }
        .letterhead { text-align: center; margin-bottom: 8px; }
        .letterhead h1 { font-size: 16px; margin: 0; text-transform: uppercase; }
        .letterhead .sub { font-size: 10.5px; margin: 2px 0; color: #374151; }
        .title { text-align: center; font-size: 13px; font-weight: bold; text-transform: uppercase;
                 border-top: 2px solid #111827; border-bottom: 2px solid #111827; padding: 5px 0; margin: 10px 0 4px; }
        .subtitle { text-align: center; font-size: 11px; font-weight: bold; margin-bottom: 10px; letter-spacing: 0.5px; }
        .info-box { border: 1px solid #111827; padding: 8px; margin-bottom: 10px; }
        .info-box table { width: 100%; border-collapse: collapse; }
        .info-box td { padding: 2px 4px; font-size: 10.5px; vertical-align: top; }
        .info-label { color: #374151; width: 100px; }
        .info-value { font-weight: bold; width: 340px; }
        .content-box { border: 1px solid #e5e7eb; padding: 10px; margin-bottom: 10px; min-height: 200px; }
        .content-box p { font-size: 11px; line-height: 1.5; white-space: pre-line; margin: 0; }
        .end-of-report { text-align: center; font-size: 10px; color: #374151; margin: 16px 0; }
        .signoff table { width: 100%; margin-top: 20px; }
        .signoff td { font-size: 10.5px; vertical-align: top; padding-top: 10px; }
        .footer { margin-top: 24px; font-size: 9px; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 6px; }
    </style>
</head>
<body>
    <div class="letterhead">
        <h1>{{ $hospital->hospital_name ?: 'Smart Hospital' }}</h1>
        @if($hospital->address)<p class="sub">{{ $hospital->address }}</p>@endif
        @if($hospital->phone_number || $hospital->email)
            <p class="sub">
                @if($hospital->phone_number) Ph: {{ $hospital->phone_number }} @endif
                @if($hospital->phone_number && $hospital->email) &middot; @endif
                @if($hospital->email) {{ $hospital->email }} @endif
            </p>
        @endif
    </div>

    <div class="title">Medical Report</div>
    <p class="subtitle">{{ strtoupper($report->report_type ?? '—') }}</p>

    <div class="info-box">
        <table>
            <tr>
                <td class="info-label">Patient Name</td><td class="info-value">{{ $patient?->fullName() ?? '—' }}</td>
                <td class="info-label">Report No</td><td class="info-value">{{ $report->report_id }}</td>
            </tr>
            <tr>
                <td class="info-label">Patient ID</td><td class="info-value">{{ $patient?->patient_id ?? $report->patient_id ?? '—' }}</td>
                <td class="info-label">Record No</td><td class="info-value">{{ $report->medical_record_id ?? '—' }}</td>
            </tr>
            <tr>
                <td class="info-label">Gender / Age</td>
                <td class="info-value">
                    {{ $patient?->gender ? ucfirst($patient->gender) : '—' }}
                    @if($patient?->date_of_birth) / {{ \Carbon\Carbon::parse($patient->date_of_birth)->age }} Y @endif
                </td>
                <td class="info-label">Reported Dt</td>
                <td class="info-value">{{ $report->generated_at ? \Carbon\Carbon::parse($report->generated_at)->format('d/m/Y h:i A') : '—' }}</td>
            </tr>
            <tr>
                <td class="info-label">Attending Physician</td><td class="info-value" colspan="3">Dr. {{ $doctorName ?? '—' }}</td>
            </tr>
        </table>
    </div>

    <div class="content-box">
        <p>{{ $report->report_content ?: '—' }}</p>
    </div>

    <p class="end-of-report">-------------------------------------------- END OF REPORT --------------------------------------------</p>

    <div class="signoff">
        <table>
            <tr>
                <td style="width: 50%;">
                    Generated By: {{ $generatedByName ?? '—' }}
                </td>
                <td style="width: 50%;">
                    Authorized by<br>
                    <strong>Dr. {{ $doctorName ?? '—' }}</strong>
                </td>
            </tr>
        </table>
    </div>

    <p class="footer">
        Generated by {{ $hospital->hospital_name ?: 'Smart Hospital' }} Management System on
        {{ $report->generated_at ? \Carbon\Carbon::parse($report->generated_at)->format('d/m/Y h:i A') : '—' }}
    </p>
</body>
</html>
